on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.makedev.com.au
        username: gitactions@makedev.com.au
        password: ${{ secrets.password }}
        exclude: .git*
          - **.git*
          - .git*/**
          -  **/.git*/**
          - node_modules/**
          - node_modules/**/*
